CREATE TABLE Palaute
(palaute_id INTEGER (10)NOT NULL AUTO_INCREMENT
,nimi VARCHAR (100) NOT NULL
,email VARCHAR (100)
,otsikko VARCHAR (100) NOT NULL
,palaute VARCHAR (1000) NOT NULL
,luettu BOOLEAN DEFAULT FALSE
,PRIMARY KEY (palaute_id)
)ENGINE=InnoDB;